### ISSUE TITLE
Utilise DBs for File Types

### ISSUE THREAD

**Issue by barncastle** [Marlamin/wow.tools#32]
It's probably worth adding `TextureFileData.db2` and `ModelFileData.db2` to the `updateTypes` script. This'll help with the mass of encrypted files and *possibly* speed up new build analysis.

**Comment by Marlamin** [comment]
Yup, great idea. Will hook them up to files page as well similar to creaturemodeldata.

**Comment by Marlamin** [comment]
Also, can you please log on to Discord, there's a bunch of things you need to check
