### ISSUE TITLE
Some 4.0.1.12911 dbcs showing Russian data.

### ISSUE THREAD

**Issue by Dovvah** [Marlamin/wow.tools#39]
Noticed on worldsafelocs and map.dbc for 4.0.1.12911.
![ss+(2019-08-22+at+08 36 37)](https://user-images.githubusercontent.com/37161147/63526018-4c0c0100-c4c4-11e9-965c-09c3a44a1279.png)

**Comment by Marlamin** [comment]
This should be fixed now!
