### ISSUE TITLE
8.2.5 31961 ItemSparse - Item Quality

### ISSUE THREAD

**Issue by Rokeo** [Marlamin/wow.tools#46]
Can you please check if parsing of ItemSparse working correctly on last release build 31961?

I found that quality in this table got broken, for example:

https://wow.tools/dbc/?dbc=itemsparse&build=8.2.5.31961#search=167012&page=1
this item Uncommon quality (green), but in table it have value **110**, while wow quality are from 0 to 8

similar for anchor weed for example:
https://wow.tools/dbc/?dbc=itemsparse&build=8.2.5.31961#search=152510&page=1
quality from DB is **0**, while should be 2 (Uncommon)

Thanks!

**Comment by Marlamin** [comment]
Yeah, something definitely broke somewhere. Thanks!

**Comment by Marlamin** [comment]
Should be fixed now, can you try again?

**Comment by Rokeo** [comment]
will be checking right away, thanks!

**Comment by Rokeo** [comment]
btw does only this table was broken or some other too?

**Comment by Marlamin** [comment]
It is definitely possible this has happened for more DBs as well. Basically, when Blizzard converts a field to an array we generally don't notice due to layouthash not updating. Need to add something to definition merger that deals with this.

**Comment by Rokeo** [comment]
Got you!

**Comment by Rokeo** [comment]
anyway this one looks like fixed!

**Comment by Rokeo** [comment]
p.s. can you tell which other tables you updated (which were bugged)?

**Comment by Marlamin** [comment]
That's the only one so far I've seen this build but there might be more. Need to work on a solution to detect these kind of changes.
