### ISSUE TITLE
File queue issues

### ISSUE THREAD

**Issue by barncastle** [Marlamin/wow.tools#48]
Sorry I think I broke the file queue 😢
Attached are all the map related files might be better to just bulk db upload or something - [unshipped.txt](https://github.com/Marlamin/wow.tools/files/3699943/unshipped.txt)

**Comment by Marlamin** [comment]
Yeah maybe don't submit -that- many files at once. :D

**Comment by Marlamin** [comment]
Also you should probably be on Discord during stuff like this

**Comment by Marlamin** [comment]
Looks like the import on these is okay, you did manage to crash MySQL there for a second, though.

**Comment by Marlamin** [comment]
Next time smaller batches of like 2000 would be good, thanks!
