### ISSUE TITLE
Files page search filter issue

### ISSUE THREAD

**Issue by barncastle** [Marlamin/wow.tools#49]
I've got a great bug here!

On the files page if you filter by `unnamed,type:m2` you get `x of 286 entries` but if you swap it to `type:m2,unnamed` you get `x of 755 entries` (this one is wrong).

As far as I can tell this only happens when these two filters - no other filter/type combination seems to do this.

**Comment by Marlamin** [comment]
Fixed in bc1ec75, thanks!
