### ISSUE TITLE
Error 1005 Access denied

### ISSUE THREAD

**Issue by Meivyn** [Marlamin/wow.tools#50]
I'm receiving this message when I'm trying to browse wow.tools since today:
![image](https://user-images.githubusercontent.com/793322/71306319-b7031100-23ac-11ea-90f7-b03baac91f5a.png)
I'm using Mullvad VPN, so it must be because of the VPN.

Are you blocking some VPN providers? If so, why? Can you consider unblocking it?

**Comment by Marlamin** [comment]
There was a bunch of crawling coming through several VPNs including that one that affected site performance. I'll consider unblocking it later after I've fixed the performance hole.

**Comment by Meivyn** [comment]
I understand, do you have any ETA? Meanwhile I'll just turn it off when I need to use your website. It's a useful one for add-ons developers.

**Comment by Marlamin** [comment]
With a little luck the bans will be lifted and the functionality re-enabled later today.

**Comment by Meivyn** [comment]
Then you can close this. I'll just wait, I was reporting it in case there was something wrong with your filtering. Thanks for your hard work.

**Comment by Marlamin** [comment]
:+1:
