### ISSUE TITLE
Itemeffects DB actual data 8.3 33073 partially missing 

### ISSUE THREAD

**Issue by Rokeo** [Marlamin/wow.tools#54]
Hi! Was checking for new items from patch 8.3 other day and found that for some reason existing itemeffects DB stated as 8.3.0.33073  do not have information on new items
for example:
https://wow.tools/dbc/?dbc=itemeffect&build=8.3.0.33073#search=173403&page=1

However it exist in wowhead, so it should be in database (It was added in patch 33062):
https://www.wowhead.com/item=173403/black-empire-mail-helm&bonus=0

So my question is it possible not full database was parsed or something got broken?

**Comment by Marlamin** [comment]
Are you certain that it is supposed to have an itemeffect? It seems to be a container of some sorts. This might be handled through flags in ItemSparse or something like that.

**Comment by Rokeo** [comment]
i think so, as this is on use item, which have spell to create actual gear (if you can check it in game or any similar you can see on use tooltip for it), so as it have on use effect (which is always spell)

**Comment by Marlamin** [comment]
If Wowhead has a spell connected to the item through ItemEffects it usually shows up on hover on the relevant part of the tooltip which it doesn't here. I think this might just not have a spell connected to it. Other armor tokens/containers on Wowhead don't have an effect connected to it either e.g. [this one](https://www.wowhead.com/item=151557/champions-strongbox).

So not sure how this works, but I don't think it is an item effect or a DBC parsing issue.

**Comment by Marlamin** [comment]
Hackfixed in a quick flag viewer for ItemSparse flags.

The item in question has the following flags:
```
HEROIC_TOOLTIP
ITEM_PURCHASE_RECORD
NO_DISENCHANT
IS_BOUND_TO_ACCOUNT
SHOW_BEFORE_DISCOVERED
OVERRIDE_GOLD_COST
BNET_ACCOUNT_TRADE_OK
DONT_DISPLAY_IN_GUILD_NEWS
PUSH_LOOT
CREATE_LOOT_IMMEDIATELY
GENERATE_LOOT_SPEC_ITEM
```
I'm assuming one of those generates the <Right click to use> part of the tooltip, but not sure.

**Comment by Marlamin** [comment]
This apparently shows up on push_loot, not a bug.

**Comment by Rokeo** [comment]
Thank you!

**Comment by Rokeo** [comment]
so this is from (https://wow.tools/dbc/?dbc=itemsparse&build=8.3.0.33073#search=&page=1)
Flags[0] | Flags[1] | Flags[2] | Flags[3]?

Can you show full enums of possible values also?

**Comment by Marlamin** [comment]
Not on the site right now, we're planning on implementing this in DBDs but for now you'll have to check source.

https://github.com/Marlamin/wow.tools/blob/master/dbc/js/dbc.js

**Comment by Rokeo** [comment]
Thank you

**Comment by Rokeo** [comment]
do you possibly know flag to check if certain mob can't be stunned or not?

**Comment by Marlamin** [comment]
Nope
