### ISSUE TITLE
Js Error: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by barncastle** [Marlamin/wow.tools#56]
https://github.com/Marlamin/wow.tools/blob/141ad2f4a5ce58463b8dfd0970bb02c44c01b1ff/files/index.php#L383

I think this should be referencing DataTable:
```js
$('#files').DataTable().ajax.url("/casc/filetable/files?buildConfig=" + build).draw(false); 
```

**Comment by Marlamin** [comment]
I think that was dead code anyways, removed, thanks for the report!
