### ISSUE TITLE
Is it possible to download only build.info? [Question]

### ISSUE THREAD

**Issue by Rokeo** [Marlamin/wow.tools#58]
Is it possible to download only **build.info** for wow particular build (for example retail)?

I do get new wow.exe from CASCExplorer when new build comes, but there is no build.info so i can't use local storage for CASC, which works much faster then online obviously, as it take build info information from wow folder.

Thank you!

p.s. i do not use battle.net launcher

**Comment by Marlamin** [comment]
You can likely build your own .build.info from the information available on WoW.tools and other official sources (e.g. the configs).

It won't be able to give you a .build.info to download as some things it can't know about (e.g locale, account language, system language etc).
