### ISSUE TITLE
listfile - updated for shadowlands?

### ISSUE THREAD

**Issue by Rokeo** [Marlamin/wow.tools#66]
Hey! 
I just checked listfile (https://wow.tools/casc/listfile/download/csv)
and it does not contain Doodad with id: 3921762 (part of "world/wmo/autogen-names/sinfall/13653.wmo)

Can you tell if this file is updated for Shadowlands or maybe not fully?

**Comment by Marlamin** [comment]
That's not an official filename, you need the unverified listfile which includes that one.

https://wow.tools/casc/listfile/download/csv/unverified

**Comment by Rokeo** [comment]
thank you!
