### ISSUE TITLE
search on map tab

### ISSUE THREAD

**Issue by cblpop** [Marlamin/wow.tools#67]
Sorry for bad english:)
I think it would be cool to get rid of exact letters in search tab when you search map.
I mean for example i want to search "Pandaria", but if i write "pan" it would find nothing, i need to write "Pan" with uppercase. So the problem goes bigger when you dont know how exactly map named (i mean where uppercases or not).
So if uppercases would not affect search would be epic cool.
ty 👍

**Comment by Marlamin** [comment]
Are you talking about the search on https://wow.tools/maps/? I am able to get the same results searching for pan and Pan.

**Comment by cblpop** [comment]
No, sry, i mean in program itself, which you download from this link https://wow.tools/export/  :)

**Comment by Marlamin** [comment]
Ah, in that case you should use this repo: https://github.com/Kruithne/wow.export
