### ISSUE TITLE
Select Language Zone not work on Classic 1.3.x and TBC 2.5.x DBC table

### ISSUE THREAD

**Issue by tywtyw2002** [Marlamin/wow.tools#71]
Hey,

It seems like the language zone not work on Classic 1.3.x and TBC 2.5.x DBC table. I select the zh_cn, ruRU, but the table still shows the Item name in English. (PS. In 9.05 the language works)

<img width="1103" alt="Screen Shot 2021-03-24 at 11 05 02 " src="https://user-images.githubusercontent.com/576954/112353247-31e26800-8c91-11eb-9b66-2dcd9e5f9f9a.png">

<img width="1085" alt="Screen Shot 2021-03-24 at 11 05 25 " src="https://user-images.githubusercontent.com/576954/112353223-28f19680-8c91-11eb-941a-34d435a28006.png">

**Comment by Marlamin** [comment]
Hey! Thanks for the report. This should be fixed now!

**Comment by tywtyw2002** [comment]
> Hey! Thanks for the report. This should be fixed now!

Thx.

And is possible to download *.db2 with a different region? Right now it only can download the US region.

**Comment by Marlamin** [comment]
From the files page you can only download enUS/generic locale versions.

There is an unadvertised endpoint that can feed you DB2s for other locales, but only DB2s.

https://wow.tools/casc/file/db2/?tableName=map&fullBuild=2.5.1.38043&locale=zhCN
