### ISSUE TITLE
Little CSS misstake

### ISSUE THREAD

**Issue by LordMagnum** [Marlamin/wow.tools#80]
https://github.com/Marlamin/wow.tools/blob/ee23131621fcb40de0a72afbc8f26f68ea0e641d/css/style.css#L172

**Comment by LordMagnum** [comment]
And more:
https://github.com/Marlamin/wow.tools/blob/master/db/css/style.css#L24

https://github.com/LordMagnum/wow.tools/blob/patch-1/files/css/files.css#L75

https://github.com/LordMagnum/wow.tools/blob/patch-1/maps/css/style.css#L201

https://github.com/LordMagnum/wow.tools/blob/patch-1/mv/modelviewer.css#L218

https://github.com/LordMagnum/wow.tools/blob/patch-1/mv/modelviewer.css#L281

that's it for now.

**Comment by Marlamin** [comment]
I don't see the issue exactly, can you be more specific?

**Comment by LordMagnum** [comment]
the hex color code has one value too much for simple RGB

**Comment by Marlamin** [comment]
Yeah, it's RGBA

**Comment by LordMagnum** [comment]
Ahh crap, sorry. I didn't know it like that before.
https://www.w3.org/TR/css-color-4/#typedef-hex-color
