### ISSUE TITLE
couple new enum guesses

### ISSUE THREAD

**Issue by Shauren** [Marlamin/wow.tools#83]
176,185,186,189,193 - filled the sheet

**Comment by Marlamin** [comment]
I have no clue how you managed to find/verify some of these, but thanks! Added.

**Comment by Shauren** [comment]
Flags were easy, only more complex one was 176 where I followed spell 188501
SpellId 188501
SpellXSpellVisualID 86070
SpellVisualID 48604
SpellVisualID 52923 (from CasterSpellVisualID column)
SpellVisualEventID 117053
SpellVisualKitEffectID where ParentSpellVisualEventID =117053
All OutlineEffect and their linked hilightcolors have matching type
