### ISSUE TITLE
have china CSV?

### ISSUE THREAD

**Issue by GaaRa0** [Marlamin/wow.tools#93]
have china server CSV? some model file is not same as global server really need it like china abomination

**Comment by Marlamin** [comment]
You can export DB2s in the zhCN locale on the DB2 browser page.

**Comment by GaaRa0** [comment]
have some china CDN or listfile for some creature that have alternative
version that exclusive only china
WOW.export have error CDN on CN server

**Comment by Marlamin** [comment]
wow.tools doesn't support extraction of the alternate/low violence files, try cascexplorer maybe

**Comment by Marlamin** [comment]
Nope, wow.export doesn't support alternate models either, listfile is the same for CN models
