### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by BSarmady** [Marlamin/wow.tools#98]
I have downloaded this and trying to build a local copy (localhost) on nginx, mariadb and php 8.x

Is there an instruction manual on how to install this?

I have renamed db.php and config.php and filled the db information.

1- Still getting error memcached not found. where does it supposed to go?
2- Should I install this on root of website or can it work from a folder e.g. `//localhost/wow.tools/` ?

**Comment by Marlamin** [comment]
This project is largely abandoned and no support is given anymore.
You can try the standalone locally runnable version of the application which I also don't provide support for but does have installation instructions: https://github.com/Marlamin/wow.tools.local

**Comment by BSarmady** [comment]
Hmm, The local version is kind of broken, 

it doesn't show most models and the ones that show, look like this

![image](https://github.com/user-attachments/assets/f40bbd05-63e9-4115-af32-ec248bb51e0c)

And in its console I have thousands of these:

![image](https://github.com/user-attachments/assets/55741f0c-c749-4549-86cb-dbe2ff4c112c)

That's why I tried to run the online version which apparently is also dead.

Seems like my attempts to see on single animation all fails.

WoWModelViewer v0.9.0.680 and above all are broken and cannot load the files and the one version that I had from 2022 is crashing after clicking on a model (it was working previously)

It's such a waste that you have decided to abandon the great job you have done and decided to let its knowledge also die with it.

**Comment by Marlamin** [comment]
If there's an actual problem with the local version you can always open an issue there provided you are running it with a supported/currently available version. Keep in mind character models aren't and never were supported in either version as they use the same model viewer.

I have no responsibility to you or anyone to keep working on a certain thing and guilting someone over it isn't very cool, especially when I announced a year ahead of time that it was happening. All the code is publicly available, all the data is publicly available and all the "knowledge" contained in the project is available through either those two or the wowdev wiki, if you're skilled enough to figure that out.

**Comment by BSarmady** [comment]
I apologize make you feel that way. 

I understand. Thank you for your time
